name: Generate JSDocs for Scripts

on:
    push:
        branches:
            - dev # Adjust to your main branch name
permissions:
  contents: write
  pull-requests: write
  issues: write
jobs:
  Generate-Docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20' # Adjust to your Node.js version

      - name: Install dependencies
        run: npm ci

      - name: Generate Docs
        run: npm run jsdoc

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
            message: "Update JSDocs"
            add: "./source/project/docs/JSDocs"
            author_name: "GitHub Actions"
            author_email: "sasrinath@ucsd.edu"
              
              


              
