name: Lint-Check on PR

on:
    pull_request:
        branches:
            - dev
            - main
        types: [opened, synchronize]
    push: 
        branches:
            - dev

jobs:
  lint-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v2
        with:
          node-version: '22.2.0'
      - name: Install Dependencies
        run: npm ci
      - name: Lint Check
        run: npm run prettier:check
      - name: Run ESLint Check
        run: npm run eslint:check
