name: Testing CI/CD

on: 
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout
        uses: actions/checkout@v2

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22.2.0'

      # Install dependencies
      - name: Install dependencies
        run: npm ci

      # Run E2E tests
      - name: Run E2E tests
        run: npm run test:E2E
