name: Unit Tests

on: [push] # the Github Action will activate "on" the event that you "push" to the repo

jobs:
    tests:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4 # using version 4 of Actions
            - name: Install Dependencies
              run: npm install
            - name: Sanity Test Test
              run: npm test ./source/project/__tests__/
